apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: "docker.io/liugztat/guoyao-server_serverless:latest"
        imagePullPolicy: Always # add this line
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LISTEN_PORT
          value: "30152"
        - name: CLIENTS
          value: "10"
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-server-service
# spec:
#   type: ClusterIP
#   selector:
#     app: server
#   ports:
#   - protocol: TCP
#     port: 30152
---