global_config:
  seed: 5959
  device: "cpu"
  is_mp: True
---
data_config:
  data_path: "./src/data/femnist_v1"
  dataset_name: "MNIST"
  num_shards: 200
  iid: False
---
fed_config:
  C: 1.0  #fraction of clients
  K: 10  #num_clients 
  R: 500  #num_rounds
  E: 10   #local_epochs
  B: 64   #batch_size
  criterion: torch.nn.CrossEntropyLoss #BCELoss
  optimizer: torch.optim.SGD
  enable_test: False
---
optim_config:
  lr: 0.01
  momentum: 0.009
---
init_config:
  init_type: "normal"
  init_gain: 1.0
  gpu_ids: []
---
model_config: 
  # name: TwoNN
  # in_features: 784
  # num_hiddens: 200
  # num_classes: 64
  
  name: CNN
  in_channels: 1
  hidden_channels: 32
  num_hiddens: 512
  num_classes: 64

  # name: LogisticRegression
  # input_dim: 3
---
log_config:
  log_path: "./log/"
  log_name:  "FL.log"
  tb_port: 5252
  tb_host: "0.0.0.0"