# TODO: add sketch config
global_config:
  seed: 5959
  device: "cpu"
  is_mp: True
---
data_config:
  data_path: "./data/"
  dataset_name: "CIFAR10"
  num_shards: 200
  iid: False
---
fed_config:
  C: 1.0
  K: 10
  R: 5
  E: 1
  B: 10
  criterion: torch.nn.CrossEntropyLoss
  optimizer: torch.optim.SGD
---
optim_config:
  lr: 0.05
  momentum: 0
---
init_config:
  init_type: "xavier"
  init_gain: 1.0
  gpu_ids: []
---
model_config: 
  #name: TwoNN
  #in_features: 784
  #num_hiddens: 200
  #num_classes: 10
  
  name: CNN2
  in_channels: 3
  hidden_channels: 32
  num_hiddens: 512
  num_classes: 10
---
log_config:
  log_path: "./log/"
  log_name:  "FL.log"
  tb_port: 5252
  tb_host: "0.0.0.0"
---
sketch_config:
  sketch_c: 500000
  sketch_r: 5
  k: 50000