global_config:
  seed: 5959
  device: "cpu"
  is_mp: True
---
data_config:
  data_path: "./data"
  dataset_name: "MNIST"
  num_shards: 200
  iid: False
---
fed_config:
  C: 1.0  #fraction of clients
  K: 7  #num_clients 
  R: 500  #num_rounds
  E: 10   #local_epochs
  B: 3   #batch_size
  criterion: torch.nn.BCELoss
  optimizer: torch.optim.SGD
  enable_test: False
---
optim_config:
  lr: 0.01
  momentum: 0.9
---
init_config:
  init_type: "normal"
  init_gain: 1.0
  gpu_ids: [0, 1, 2]
---
model_config: 
  #name: TwoNN
  #in_features: 784
  #num_hiddens: 200
  #num_classes: 10
  
  # name: CNN
  # in_channels: 1
  # hidden_channels: 32
  # num_hiddens: 512
  # num_classes: 10
  name: LogisticRegression
  input_dim: 3
---
log_config:
  log_path: "./log/"
  log_name:  "FL.log"
  tb_port: 5252
  tb_host: "0.0.0.0"