apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  replicas: 10
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: "docker.io/liugztat/guoyao-client_serverless:latest"
        imagePullPolicy: Always # add this line
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: SERVER_ADDRESS
          value: my-server-service
        - name: SERVER_PORT
          value: "30152"
        - name: MODEL_SIZE
          value: "1500000"
        - name: SHARDS
          value: "3"
